import ClipShelfLocalization
import AppKit
import ClipShelfCore

@MainActor
final class CaptureService {
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var observedCount: Int
    private var selfWriteCount: Int?
    private var lastSourceBundleID: String?
    private let sourceProvider: () -> (name: String?, bundleID: String?)
    private(set) var isRunning = false
    var excludedBundleIDs: Set<String> = [] {
        didSet { if oldValue != excludedBundleIDs { resetObservation() } }
    }
    var onCapture: ((ClipboardRecord) -> Void)?
    var onStatus: ((String) -> Void)?
    static let internalType = NSPasteboard.PasteboardType("io.github.bestbbb.clipshelf.transaction")
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.ConfidentialType",
        "com.agilebits.onepassword", "com.1password.1password"
    ]

    init(pasteboard: NSPasteboard = .general, sourceProvider: @escaping () -> (name: String?, bundleID: String?) = {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.localizedName, app?.bundleIdentifier)
    }) {
        self.pasteboard = pasteboard
        self.sourceProvider = sourceProvider
        observedCount = pasteboard.changeCount
        lastSourceBundleID = sourceProvider().bundleID
    }

    func start() {
        guard !isRunning else { return }
        // Baseline before polling; starting/resuming never imports the old clipboard.
        resetObservation()
        isRunning = true
        let poller = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer = poller
        RunLoop.main.add(poller, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
        resetObservation()
    }

    func noteSelfWrite() {
        selfWriteCount = pasteboard.changeCount
        observedCount = pasteboard.changeCount
    }

    /// Clipboard APIs do not identify the writer. Discard an unobserved change
    /// spanning an excluded-app transition rather than attribute it to the new app.
    func noteFrontmostApplication(bundleID: String?) {
        guard lastSourceBundleID != bundleID else { return }
        let crossesExclusion = lastSourceBundleID.map(excludedBundleIDs.contains) == true || bundleID.map(excludedBundleIDs.contains) == true
        lastSourceBundleID = bundleID
        if crossesExclusion { observedCount = pasteboard.changeCount }
    }

    private func resetObservation() {
        observedCount = pasteboard.changeCount
        lastSourceBundleID = sourceProvider().bundleID
    }

    func poll() {
        guard isRunning else { return }
        let source = sourceProvider()
        noteFrontmostApplication(bundleID: source.bundleID)
        let count = pasteboard.changeCount
        guard count != observedCount else { return }
        observedCount = count
        guard count != selfWriteCount else { return }
        if let bundleID = source.bundleID, excludedBundleIDs.contains(bundleID) { return }
        let types = Set((pasteboard.pasteboardItems ?? []).flatMap { $0.types.map(\.rawValue) })
        guard types.isDisjoint(with: ignoredTypes), !types.contains(Self.internalType.rawValue) else { return }
        do {
            let record = try ClipboardCodec.record(from: pasteboard, sourceApp: source.name, sourceBundleID: source.bundleID)
            guard pasteboard.changeCount == count, sourceProvider().bundleID == source.bundleID else { return }
            if let record { onCapture?(record) }
        } catch { onStatus?(L10n.text("这条内容未能记录：\(error.localizedDescription)")) }
    }
}
