import ClipShelfLocalization
import AppKit
import ClipShelfCore

@MainActor
final class CaptureService {
    /// Synchronous, main-thread clipboard access. Tests can provide immutable
    /// bytes and controlled changes without reading the system pasteboard.
    struct Reader {
        var changeCount: () -> Int
        var declaredTypes: () -> Set<String>?
        var snapshot: (String?, String?) throws -> ClipboardCaptureSnapshot?
    }

    private let reader: Reader
    private var timer: Timer?
    private var processedCount: Int
    private var generation: UInt64 = 0
    private var isPolling = false
    private var retryCount: Int?
    private var retryAttempts = 0
    private var ambiguousSourceCount: Int?
    private var lastSourceBundleID: String?
    private let sourceProvider: () -> (name: String?, bundleID: String?)
    private(set) var isRunning = false
    var excludedBundleIDs: Set<String> = [] {
        didSet { if oldValue != excludedBundleIDs { resetObservation() } }
    }
    var onSnapshot: ((ClipboardCaptureSnapshot) -> Void)?
    var onStatus: ((String) -> Void)?
    static let internalType = NSPasteboard.PasteboardType("io.github.bestbbb.clipshelf.transaction")
    static let maximumReadAttempts = 3
    private let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.ConfidentialType",
        "com.agilebits.onepassword", "com.1password.1password"
    ]

    convenience init(pasteboard: NSPasteboard = .general, sourceProvider: @escaping () -> (name: String?, bundleID: String?) = {
        let app = NSWorkspace.shared.frontmostApplication
        return (app?.localizedName, app?.bundleIdentifier)
    }) {
        self.init(reader: Reader(
            changeCount: { pasteboard.changeCount },
            declaredTypes: { pasteboard.pasteboardItems.map { Set($0.flatMap { $0.types.map(\.rawValue) }) } },
            snapshot: { try ClipboardCodec.snapshot(from: pasteboard, sourceApp: $0, sourceBundleID: $1) }
        ), sourceProvider: sourceProvider)
    }

    init(reader: Reader, sourceProvider: @escaping () -> (name: String?, bundleID: String?)) {
        self.reader = reader
        self.sourceProvider = sourceProvider
        processedCount = reader.changeCount()
        lastSourceBundleID = sourceProvider().bundleID
    }

    func start() {
        guard !isRunning else { return }
        isRunning = true
        // Starting/resuming never imports the old clipboard.
        guard resetObservation(), isRunning else { return }
        let poller = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer = poller
        RunLoop.main.add(poller, forMode: .common)
    }

    func stop() {
        generation &+= 1
        timer?.invalidate()
        timer = nil
        isRunning = false
        clearRetries()
    }

    /// A foreground app is an attribution hint, not proof of the writer. An
    /// unobserved copy spanning allowed apps remains usable without attribution;
    /// crossing an excluded app discards it, including A → excluded → A.
    func noteFrontmostApplication(bundleID: String?) {
        guard lastSourceBundleID != bundleID else { return }
        let crossesExclusion = lastSourceBundleID.map(excludedBundleIDs.contains) == true || bundleID.map(excludedBundleIDs.contains) == true
        generation &+= 1
        let current = generation
        lastSourceBundleID = bundleID
        let count = reader.changeCount()
        guard generation == current else { return }
        if crossesExclusion {
            finishObservation(count)
        } else if count != processedCount {
            ambiguousSourceCount = count
        }
    }

    @discardableResult private func resetObservation() -> Bool {
        generation &+= 1
        let current = generation
        let source = sourceProvider()
        guard generation == current else { return false }
        let count = reader.changeCount()
        guard generation == current else { return false }
        lastSourceBundleID = source.bundleID
        finishObservation(count)
        return true
    }

    private func clearRetries() { retryCount = nil; retryAttempts = 0 }
    private func exhaustedReadAttempts(for count: Int) -> Bool {
        if retryCount != count { retryCount = count; retryAttempts = 0 }
        retryAttempts += 1
        return retryAttempts >= Self.maximumReadAttempts
    }
    private func finishObservation(_ count: Int) {
        processedCount = count
        ambiguousSourceCount = nil
        clearRetries()
    }
    private func isCurrent(_ current: UInt64) -> Bool { isRunning && generation == current }

    /// Reentrant callbacks can stop/start capture or change policy while a
    /// promised representation is being read. Never deliver that old observation.
    private func readIsCurrent(_ current: UInt64, count: Int, sourceBundleID: String?) -> Bool {
        guard isCurrent(current) else { return false }
        let after = sourceProvider()
        guard isCurrent(current) else { return false }
        if after.bundleID != sourceBundleID {
            noteFrontmostApplication(bundleID: after.bundleID)
            return false
        }
        let afterCount = reader.changeCount()
        return isCurrent(current) && afterCount == count
    }

    private func observationMayBeCaptured(_ current: UInt64, count: Int, sourceBundleID: String?) -> Bool {
        guard readIsCurrent(current, count: count, sourceBundleID: sourceBundleID) else { return false }
        let types = reader.declaredTypes() ?? []
        guard readIsCurrent(current, count: count, sourceBundleID: sourceBundleID) else { return false }
        if sourceBundleID.map(excludedBundleIDs.contains) == true || !types.isDisjoint(with: ignoredTypes) || types.contains(Self.internalType.rawValue) {
            finishObservation(count)
            return false
        }
        return true
    }

    func poll() {
        guard isRunning, !isPolling else { return }
        isPolling = true
        defer { isPolling = false }
        let beforeSource = generation
        let source = sourceProvider()
        guard isCurrent(beforeSource) else { return }
        noteFrontmostApplication(bundleID: source.bundleID)
        let current = generation
        guard isCurrent(current) else { return }
        let count = reader.changeCount()
        guard isCurrent(current), count != processedCount else { return }
        guard observationMayBeCaptured(current, count: count, sourceBundleID: source.bundleID) else { return }
        do {
            let uncertainSource = ambiguousSourceCount == count || source.bundleID == nil
            let readSnapshot = try reader.snapshot(uncertainSource ? nil : source.name, uncertainSource ? nil : source.bundleID)
            guard observationMayBeCaptured(current, count: count, sourceBundleID: source.bundleID) else { return }
            // Empty items may be a temporarily unavailable promise. Retry the
            // same count, but a genuinely empty clipboard expires quietly.
            guard var snapshot = readSnapshot else {
                if exhaustedReadAttempts(for: count) { finishObservation(count) }
                return
            }
            if uncertainSource { snapshot.sourceApp = nil; snapshot.sourceBundleID = nil }
            // Capture ingestion now owns the complete frozen bytes.
            finishObservation(count)
            onSnapshot?(snapshot)
        } catch {
            guard observationMayBeCaptured(current, count: count, sourceBundleID: source.bundleID) else { return }
            if case ClipboardCodecError.temporarilyUnavailable = error {
                guard exhaustedReadAttempts(for: count) else { return }
            }
            // A poison item cannot stall future clipboard changes or produce a
            // status on every poll. A changed count gets its own bounded attempts.
            finishObservation(count)
            onStatus?(L10n.text("这条内容未能记录：\(error.localizedDescription)"))
        }
    }
}
