import ClipShelfLocalization
import AppKit
import ClipShelfCore
import UniformTypeIdentifiers
import ImageIO

enum ClipboardCodecError: LocalizedError {
    case tooLarge, unavailableFile, noContent, temporarilyUnavailable
    var errorDescription: String? {
        switch self {
        case .temporarilyUnavailable: return L10n.text("剪贴板内容暂时无法完整读取。")
        case .tooLarge: return L10n.text("内容超过本次采集的 64 MB 上限。")
        case .unavailableFile: return L10n.text("文件已移动或不可访问，请在“文件与位置…”中查看并重新定位。")
        case .noContent: return L10n.text("没有可用的剪贴板表示。")
        }
    }
}

/// Converts only the supplied pasteboard. The caller enforces privacy before reading payloads.
@MainActor
enum ClipboardCodec {
    enum SnapshotPolicy: Sendable { case passiveCapture, explicitImport }
    nonisolated static let maximumCaptureBytes = 64 * 1_024 * 1_024
    nonisolated static let maximumOutputBytes = 512 * 1_024 * 1_024

    static func snapshot(from pasteboard: NSPasteboard, sourceApp: String?, sourceBundleID: String?,
                         policy: SnapshotPolicy = .passiveCapture) throws -> ClipboardCaptureSnapshot? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return nil }
        return try snapshot(from: items, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: policy)
    }

    static func snapshot(from items: [NSPasteboardItem], sourceApp: String?, sourceBundleID: String?,
                         policy: SnapshotPolicy = .passiveCapture) throws -> ClipboardCaptureSnapshot? {
        let copiedAt = Date()
        let sensitive = Set(["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.ConfidentialType",
                             "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.1password.1password"])
        // Freeze every item's declaration before reading any payload. A marker on
        // a later item must protect all earlier items in the same interaction.
        let declarations = items.map { item -> [NSPasteboard.PasteboardType] in
            var seen: Set<String> = []
            return item.types.filter { seen.insert($0.rawValue).inserted }
        }
        guard declarations.allSatisfy({ Set($0.map(\.rawValue)).isDisjoint(with: sensitive) }) else { return nil }
        if policy == .passiveCapture, declarations.contains(where: { $0.contains(CaptureService.internalType) }) { return nil }
        var parts: [ClipboardPart] = []
        var byteCount = 0
        for (item, types) in zip(items, declarations) {
            var representations: [ClipboardRepresentation] = []
            for type in types where type != CaptureService.internalType && type != OwnedFilePublicationCoordinator.pasteboardType && type.rawValue != "io.github.bestbbb.clipshelf.record-id" {
                guard let data = item.data(forType: type) else { throw ClipboardCodecError.temporarilyUnavailable }
                guard data.count <= maximumCaptureBytes - byteCount else { throw ClipboardCodecError.tooLarge }
                byteCount += data.count
                representations.append(ClipboardRepresentation(typeIdentifier: type.rawValue, data: data))
            }
            if !representations.isEmpty { parts.append(ClipboardPart(representations: representations)) }
        }
        guard !parts.isEmpty else { return nil }
        return ClipboardCaptureSnapshot(parts: parts, sourceApp: sourceApp, sourceBundleID: sourceBundleID,
                                        copiedAt: copiedAt, byteCount: byteCount)
    }

    static func record(from pasteboard: NSPasteboard, sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        guard let value = try snapshot(from: pasteboard, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: .explicitImport) else { return nil }
        return try record(from: value)
    }

    static func record(from items: [NSPasteboardItem], sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        guard let value = try snapshot(from: items, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: .explicitImport) else { return nil }
        return try record(from: value)
    }

    nonisolated static func record(from snapshot: ClipboardCaptureSnapshot) throws -> ClipboardRecord {
        guard !snapshot.parts.isEmpty else { throw ClipboardCodecError.noContent }
        var textParts: [String] = []
        var byteCount = 0
        for part in snapshot.parts {
            guard !part.representations.isEmpty else { throw ClipboardCodecError.noContent }
            for representation in part.representations {
                guard representation.data.count <= maximumCaptureBytes - byteCount else { throw ClipboardCodecError.tooLarge }
                byteCount += representation.data.count
            }
            func data(_ type: String) -> Data? { part.representations.first { $0.typeIdentifier == type }?.data }
            func string(_ type: String) -> String? { data(type).flatMap { String(data: $0, encoding: .utf8) } }
            if let fileString = string("public.file-url"), let url = URL(string: fileString) {
                textParts.append(url.lastPathComponent)
            } else if let text = string("public.utf8-plain-text"), !text.isEmpty {
                textParts.append(text)
            } else if let link = string("public.url"), !link.isEmpty {
                textParts.append(link)
            } else if let image = data("public.png") ?? data("public.tiff"),
                      let source = CGImageSourceCreateWithData(image as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
                      let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                      let width = properties[kCGImagePropertyPixelWidth] as? NSNumber,
                      let height = properties[kCGImagePropertyPixelHeight] as? NSNumber,
                      width.intValue > 0, height.intValue > 0 {
                textParts.append("图片 \(width.intValue) × \(height.intValue)")
            } else if data("com.adobe.pdf") != nil || data("public.pdf") != nil {
                textParts.append("扫描文稿（PDF）")
            } else { textParts.append("复制的内容") }
        }
        let singlePart = snapshot.parts.count == 1 ? snapshot.parts.first : nil
        let rtf = singlePart?.representations.first { $0.typeIdentifier == "public.rtf" }?.data
        let html = singlePart?.representations.first { $0.typeIdentifier == "public.html" }?.data
        return ClipboardRecord(text: textParts.joined(separator: "\n"), sourceApp: snapshot.sourceApp,
                               sourceBundleID: snapshot.sourceBundleID, copiedAt: snapshot.copiedAt,
                               rtf: rtf, html: html, parts: snapshot.parts)
    }

    static func items(for records: [ClipboardRecord], plainText: Bool,
                      encodeCombinedRTF: ((NSAttributedString) throws -> Data)? = nil,
                      maximumCombinedBytes: Int = maximumOutputBytes) throws -> [NSPasteboardItem] {
        guard !records.isEmpty else { throw ClipboardCodecError.noContent }
        if plainText {
            var contents: [String] = []
            var byteCount = 0
            for record in records {
                guard let text = ClipboardTextProjection.text(in: record) else { throw ClipboardCodecError.noContent }
                let separatorBytes = contents.isEmpty ? 0 : 1
                guard separatorBytes <= maximumOutputBytes - byteCount,
                      text.utf8.count <= maximumOutputBytes - byteCount - separatorBytes else {
                    throw HistoryStoreError.selectionPayloadTooLarge
                }
                byteCount += separatorBytes + text.utf8.count
                contents.append(text)
            }
            let item = NSPasteboardItem()
            item.setString(contents.joined(separator: "\n"), forType: .string)
            mark(item)
            return [item]
        }
        if let combined = combinedTextItem(for: records, encodeRTF: encodeCombinedRTF,
                                           maximumBytes: maximumCombinedBytes) { return [combined] }
        var result: [NSPasteboardItem] = []
        for record in records {
            if !record.parts.isEmpty {
                for part in record.parts {
                    let item = NSPasteboardItem()
                    for representation in part.representations {
                        let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
                        if ClipboardFileAccess.isFileURLType(representation.typeIdentifier) {
                            guard let url = ClipboardFileAccess.url(from: representation.data),
                                  ClipboardFileAccess.availability(of: url) == .available else { throw ClipboardCodecError.unavailableFile }
                        }
                        guard item.setData(representation.data, forType: type) else { throw ClipboardCodecError.noContent }
                    }
                    mark(item)
                    result.append(item)
                }
            } else {
                let item = NSPasteboardItem()
                guard item.setString(record.text, forType: .string) else { throw ClipboardCodecError.noContent }
                if let rtf = record.rtf, !item.setData(rtf, forType: .rtf) { throw ClipboardCodecError.noContent }
                if let html = record.html, !item.setData(html, forType: .html) { throw ClipboardCodecError.noContent }
                mark(item)
                result.append(item)
            }
        }
        guard !result.isEmpty else { throw ClipboardCodecError.noContent }
        return result
    }

    /// Combining is allowed only when every record is one complete ordinary text object.
    /// One unsupported record keeps the entire selection in its original object order.
    private static func combinedTextItem(for records: [ClipboardRecord],
                                         encodeRTF: ((NSAttributedString) throws -> Data)?,
                                         maximumBytes: Int) -> NSPasteboardItem? {
        guard records.count > 1 else { return nil }
        let byteLimit = min(max(0, maximumBytes), maximumOutputBytes)
        let combined = NSMutableAttributedString(string: "")
        for (index, record) in records.enumerated() {
            guard let text = combinableText(in: record) else { return nil }
            if index > 0 { combined.append(NSAttributedString(string: "\n")) }
            combined.append(text)
        }
        let textByteCount = combined.string.utf8.count
        guard textByteCount <= byteLimit else { return nil }
        let rtf: Data
        do {
            if let encodeRTF { rtf = try encodeRTF(combined) }
            else {
                rtf = try combined.data(from: NSRange(location: 0, length: combined.length),
                                        documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf])
            }
        } catch { return nil } // Keep original rich payloads rather than silently dropping RTF.
        // Encoding can grow past the selection's original-byte preflight. This bounds
        // published UTF-8 plus RTF bytes, not the conversion's peak resident memory.
        guard rtf.count <= byteLimit - textByteCount else { return nil }
        let item = NSPasteboardItem()
        guard item.setString(combined.string, forType: .string), item.setData(rtf, forType: .rtf) else { return nil }
        mark(item)
        return item
    }

    private static func combinableText(in record: ClipboardRecord) -> NSAttributedString? {
        guard record.html == nil else { return nil }
        let text: String
        let rtf: Data?
        if record.parts.isEmpty {
            text = record.text; rtf = record.rtf
        } else {
            guard record.parts.count == 1 else { return nil }
            let representations = record.parts[0].representations
            let types = Set(representations.map(\.typeIdentifier))
            guard !representations.isEmpty, types.count == representations.count,
                  types.isSubset(of: [NSPasteboard.PasteboardType.string.rawValue,
                                     NSPasteboard.PasteboardType.rtf.rawValue]) else { return nil }
            // The part is authoritative: a stale top-level RTF projection cannot replace it.
            rtf = representations.first { $0.typeIdentifier == NSPasteboard.PasteboardType.rtf.rawValue }?.data
            if let bytes = representations.first(where: { $0.typeIdentifier == NSPasteboard.PasteboardType.string.rawValue })?.data {
                guard let decoded = String(data: bytes, encoding: .utf8), decoded == record.text else { return nil }
                text = decoded
            } else {
                guard rtf != nil else { return nil }
                text = record.text // Verified against the decoded RTF below, never used as a fallback.
            }
        }
        guard let rtf else { return NSAttributedString(string: text) }
        // Reuse the existing conservative RTF control-word boundary before native decoding;
        // an attachment ignored by the native importer must not disappear during combination.
        let richPart = ClipboardPart(representations: [.init(typeIdentifier: "public.rtf", data: rtf)])
        guard (try? ClipboardPartEdit.validateEditablePart(richPart)) != nil,
              let rich = NSAttributedString(rtf: rtf, documentAttributes: nil), rich.string == text,
              !rich.string.contains("\u{FFFC}") else { return nil }
        var hasAttachment = false
        rich.enumerateAttribute(.attachment, in: NSRange(location: 0, length: rich.length)) { value, _, stop in
            if value != nil { hasAttachment = true; stop.pointee = true }
        }
        return hasAttachment ? nil : rich
    }

    private static func mark(_ item: NSPasteboardItem) {
        item.setString(UUID().uuidString, forType: CaptureService.internalType)
    }

    static func markPublication(_ id: UUID, in items: [NSPasteboardItem]) {
        for item in items { item.setString(id.uuidString, forType: OwnedFilePublicationCoordinator.pasteboardType) }
    }

    static func supportsPlainText(_ record: ClipboardRecord) -> Bool {
        ClipboardTextProjection.text(in: record) != nil
    }
}
