import AppKit
import ClipShelfCore
import UniformTypeIdentifiers

enum ClipboardCodecError: LocalizedError {
    case tooLarge, unavailableFile, noContent
    var errorDescription: String? {
        switch self {
        case .tooLarge: return "内容超过本次采集的 64 MB 上限。"
        case .unavailableFile: return "文件已移动或不可访问，请在“文件与位置…”中查看并重新定位。"
        case .noContent: return "没有可用的剪贴板表示。"
        }
    }
}

/// Converts only the supplied pasteboard. The caller enforces privacy before reading payloads.
@MainActor
enum ClipboardCodec {
    static func record(from pasteboard: NSPasteboard, sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return nil }
        return try record(from: items, sourceApp: sourceApp, sourceBundleID: sourceBundleID)
    }

    static func record(from items: [NSPasteboardItem], sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        let sensitive = Set(["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.ConfidentialType",
                             "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.1password.1password"])
        guard items.allSatisfy({ Set($0.types.map(\.rawValue)).isDisjoint(with: sensitive) }) else { return nil }
        var parts: [ClipboardPart] = []
        var textParts: [String] = []
        var byteCount = 0
        var rtf: Data?
        var html: Data?
        for item in items {
            var representations: [ClipboardRepresentation] = []
            for type in item.types where type != CaptureService.internalType && type.rawValue != "io.github.bestbbb.clipshelf.record-id" {
                guard let data = item.data(forType: type) else { continue }
                byteCount += data.count
                guard byteCount <= 64 * 1_024 * 1_024 else { throw ClipboardCodecError.tooLarge }
                representations.append(ClipboardRepresentation(typeIdentifier: type.rawValue, data: data))
            }
            guard !representations.isEmpty else { continue }
            parts.append(ClipboardPart(representations: representations))
            if let fileString = item.string(forType: .fileURL), let url = URL(string: fileString) {
                textParts.append(url.lastPathComponent)
            } else if let text = item.string(forType: .string), !text.isEmpty {
                textParts.append(text)
            } else if let link = item.string(forType: .URL), !link.isEmpty {
                textParts.append(link)
            } else if let image = item.data(forType: .png) ?? item.data(forType: .tiff), let size = NSImage(data: image)?.size {
                textParts.append("图片 \(Int(size.width)) × \(Int(size.height))")
            } else if item.types.contains(.pdf) || item.types.contains(.init("public.pdf")) {
                textParts.append("扫描文稿（PDF）")
            } else { textParts.append("复制的内容") }
            if items.count == 1 { rtf = item.data(forType: .rtf); html = item.data(forType: .html) }
        }
        guard !parts.isEmpty else { return nil }
        return ClipboardRecord(text: textParts.joined(separator: "\n"), sourceApp: sourceApp,
                               sourceBundleID: sourceBundleID, copiedAt: Date(), rtf: rtf, html: html, parts: parts)
    }

    static func items(for records: [ClipboardRecord], plainText: Bool) throws -> [NSPasteboardItem] {
        guard !records.isEmpty else { throw ClipboardCodecError.noContent }
        if plainText {
            guard records.allSatisfy(supportsPlainText) else { throw ClipboardCodecError.noContent }
            let item = NSPasteboardItem()
            item.setString(records.map(\.text).joined(separator: "\n"), forType: .string)
            mark(item)
            return [item]
        }
        if records.count > 1, records.allSatisfy({ [.text, .link, .color].contains($0.kind) && !$0.parts.flatMap(\.representations).contains(where: { ["com.adobe.pdf", "public.pdf"].contains($0.typeIdentifier) }) }) {
            let item = NSPasteboardItem()
            item.setString(records.map(\.text).joined(separator: "\n"), forType: .string)
            let combined = NSMutableAttributedString(string: "")
            for (index, record) in records.enumerated() {
                if index > 0 { combined.append(NSAttributedString(string: "\n")) }
                if let data = record.rtf, let attributed = NSAttributedString(rtf: data, documentAttributes: nil) {
                    combined.append(attributed)
                } else { combined.append(NSAttributedString(string: record.text)) }
            }
            if let rtf = try? combined.data(from: NSRange(location: 0, length: combined.length), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]) {
                item.setData(rtf, forType: .rtf)
            }
            mark(item)
            return [item]
        }
        var result: [NSPasteboardItem] = []
        for record in records {
            if !record.parts.isEmpty {
                for part in record.parts {
                    let item = NSPasteboardItem()
                    for representation in part.representations {
                        let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
                        if ClipboardFileAccess.isFileURLType(representation.typeIdentifier) {
                            guard let url = ClipboardFileAccess.url(from: representation.data),
                                  ClipboardFileAccess.availability(of: url) == .available else { throw ClipboardCodecError.unavailableFile }
                        }
                        item.setData(representation.data, forType: type)
                    }
                    mark(item)
                    result.append(item)
                }
            } else {
                let item = NSPasteboardItem()
                item.setString(record.text, forType: .string)
                if let rtf = record.rtf { item.setData(rtf, forType: .rtf) }
                if let html = record.html { item.setData(html, forType: .html) }
                mark(item)
                result.append(item)
            }
        }
        guard !result.isEmpty else { throw ClipboardCodecError.noContent }
        return result
    }

    private static func mark(_ item: NSPasteboardItem) {
        item.setString(UUID().uuidString, forType: CaptureService.internalType)
    }

    static func supportsPlainText(_ record: ClipboardRecord) -> Bool {
        guard record.kind != .image && record.kind != .file else { return false }
        let types = Set(record.parts.flatMap(\.representations).map(\.typeIdentifier))
        return types.isDisjoint(with: [NSPasteboard.PasteboardType.pdf.rawValue, "public.pdf"]) || types.contains(NSPasteboard.PasteboardType.string.rawValue)
    }
}
