import ClipShelfLocalization
import AppKit
import ClipShelfCore
import UniformTypeIdentifiers
import ImageIO

enum ClipboardCodecError: LocalizedError {
    case tooLarge, unavailableFile, noContent, temporarilyUnavailable
    var errorDescription: String? {
        switch self {
        case .temporarilyUnavailable: return L10n.text("剪贴板内容暂时无法完整读取。")
        case .tooLarge: return L10n.text("内容超过本次采集的 64 MB 上限。")
        case .unavailableFile: return L10n.text("文件已移动或不可访问，请在“文件与位置…”中查看并重新定位。")
        case .noContent: return L10n.text("没有可用的剪贴板表示。")
        }
    }
}

/// Converts only the supplied pasteboard. The caller enforces privacy before reading payloads.
@MainActor
enum ClipboardCodec {
    enum SnapshotPolicy: Sendable { case passiveCapture, explicitImport }
    nonisolated static let maximumCaptureBytes = 64 * 1_024 * 1_024

    static func snapshot(from pasteboard: NSPasteboard, sourceApp: String?, sourceBundleID: String?,
                         policy: SnapshotPolicy = .passiveCapture) throws -> ClipboardCaptureSnapshot? {
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return nil }
        return try snapshot(from: items, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: policy)
    }

    static func snapshot(from items: [NSPasteboardItem], sourceApp: String?, sourceBundleID: String?,
                         policy: SnapshotPolicy = .passiveCapture) throws -> ClipboardCaptureSnapshot? {
        let copiedAt = Date()
        let sensitive = Set(["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.ConfidentialType",
                             "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.1password.1password"])
        // Freeze every item's declaration before reading any payload. A marker on
        // a later item must protect all earlier items in the same interaction.
        let declarations = items.map { item -> [NSPasteboard.PasteboardType] in
            var seen: Set<String> = []
            return item.types.filter { seen.insert($0.rawValue).inserted }
        }
        guard declarations.allSatisfy({ Set($0.map(\.rawValue)).isDisjoint(with: sensitive) }) else { return nil }
        if policy == .passiveCapture, declarations.contains(where: { $0.contains(CaptureService.internalType) }) { return nil }
        var parts: [ClipboardPart] = []
        var byteCount = 0
        for (item, types) in zip(items, declarations) {
            var representations: [ClipboardRepresentation] = []
            for type in types where type != CaptureService.internalType && type != OwnedFilePublicationCoordinator.pasteboardType && type.rawValue != "io.github.bestbbb.clipshelf.record-id" {
                guard let data = item.data(forType: type) else { throw ClipboardCodecError.temporarilyUnavailable }
                guard data.count <= maximumCaptureBytes - byteCount else { throw ClipboardCodecError.tooLarge }
                byteCount += data.count
                representations.append(ClipboardRepresentation(typeIdentifier: type.rawValue, data: data))
            }
            if !representations.isEmpty { parts.append(ClipboardPart(representations: representations)) }
        }
        guard !parts.isEmpty else { return nil }
        return ClipboardCaptureSnapshot(parts: parts, sourceApp: sourceApp, sourceBundleID: sourceBundleID,
                                        copiedAt: copiedAt, byteCount: byteCount)
    }

    static func record(from pasteboard: NSPasteboard, sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        guard let value = try snapshot(from: pasteboard, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: .explicitImport) else { return nil }
        return try record(from: value)
    }

    static func record(from items: [NSPasteboardItem], sourceApp: String?, sourceBundleID: String?) throws -> ClipboardRecord? {
        guard let value = try snapshot(from: items, sourceApp: sourceApp, sourceBundleID: sourceBundleID, policy: .explicitImport) else { return nil }
        return try record(from: value)
    }

    nonisolated static func record(from snapshot: ClipboardCaptureSnapshot) throws -> ClipboardRecord {
        guard !snapshot.parts.isEmpty else { throw ClipboardCodecError.noContent }
        var textParts: [String] = []
        var byteCount = 0
        for part in snapshot.parts {
            guard !part.representations.isEmpty else { throw ClipboardCodecError.noContent }
            for representation in part.representations {
                guard representation.data.count <= maximumCaptureBytes - byteCount else { throw ClipboardCodecError.tooLarge }
                byteCount += representation.data.count
            }
            func data(_ type: String) -> Data? { part.representations.first { $0.typeIdentifier == type }?.data }
            func string(_ type: String) -> String? { data(type).flatMap { String(data: $0, encoding: .utf8) } }
            if let fileString = string("public.file-url"), let url = URL(string: fileString) {
                textParts.append(url.lastPathComponent)
            } else if let text = string("public.utf8-plain-text"), !text.isEmpty {
                textParts.append(text)
            } else if let link = string("public.url"), !link.isEmpty {
                textParts.append(link)
            } else if let image = data("public.png") ?? data("public.tiff"),
                      let source = CGImageSourceCreateWithData(image as CFData, [kCGImageSourceShouldCache: false] as CFDictionary),
                      let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
                      let width = properties[kCGImagePropertyPixelWidth] as? NSNumber,
                      let height = properties[kCGImagePropertyPixelHeight] as? NSNumber,
                      width.intValue > 0, height.intValue > 0 {
                textParts.append("图片 \(width.intValue) × \(height.intValue)")
            } else if data("com.adobe.pdf") != nil || data("public.pdf") != nil {
                textParts.append("扫描文稿（PDF）")
            } else { textParts.append("复制的内容") }
        }
        let singlePart = snapshot.parts.count == 1 ? snapshot.parts.first : nil
        let rtf = singlePart?.representations.first { $0.typeIdentifier == "public.rtf" }?.data
        let html = singlePart?.representations.first { $0.typeIdentifier == "public.html" }?.data
        return ClipboardRecord(text: textParts.joined(separator: "\n"), sourceApp: snapshot.sourceApp,
                               sourceBundleID: snapshot.sourceBundleID, copiedAt: snapshot.copiedAt,
                               rtf: rtf, html: html, parts: snapshot.parts)
    }

    static func items(for records: [ClipboardRecord], plainText: Bool) throws -> [NSPasteboardItem] {
        guard !records.isEmpty else { throw ClipboardCodecError.noContent }
        if plainText {
            guard records.allSatisfy(supportsPlainText) else { throw ClipboardCodecError.noContent }
            let item = NSPasteboardItem()
            item.setString(records.map(\.text).joined(separator: "\n"), forType: .string)
            mark(item)
            return [item]
        }
        if records.count > 1, records.allSatisfy({ [.text, .link, .color].contains($0.kind) && !$0.parts.flatMap(\.representations).contains(where: { ["com.adobe.pdf", "public.pdf"].contains($0.typeIdentifier) }) }) {
            let item = NSPasteboardItem()
            item.setString(records.map(\.text).joined(separator: "\n"), forType: .string)
            let combined = NSMutableAttributedString(string: "")
            for (index, record) in records.enumerated() {
                if index > 0 { combined.append(NSAttributedString(string: "\n")) }
                if let data = record.rtf, let attributed = NSAttributedString(rtf: data, documentAttributes: nil) {
                    combined.append(attributed)
                } else { combined.append(NSAttributedString(string: record.text)) }
            }
            if let rtf = try? combined.data(from: NSRange(location: 0, length: combined.length), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]) {
                item.setData(rtf, forType: .rtf)
            }
            mark(item)
            return [item]
        }
        var result: [NSPasteboardItem] = []
        for record in records {
            if !record.parts.isEmpty {
                for part in record.parts {
                    let item = NSPasteboardItem()
                    for representation in part.representations {
                        let type = NSPasteboard.PasteboardType(representation.typeIdentifier)
                        if ClipboardFileAccess.isFileURLType(representation.typeIdentifier) {
                            guard let url = ClipboardFileAccess.url(from: representation.data),
                                  ClipboardFileAccess.availability(of: url) == .available else { throw ClipboardCodecError.unavailableFile }
                        }
                        item.setData(representation.data, forType: type)
                    }
                    mark(item)
                    result.append(item)
                }
            } else {
                let item = NSPasteboardItem()
                item.setString(record.text, forType: .string)
                if let rtf = record.rtf { item.setData(rtf, forType: .rtf) }
                if let html = record.html { item.setData(html, forType: .html) }
                mark(item)
                result.append(item)
            }
        }
        guard !result.isEmpty else { throw ClipboardCodecError.noContent }
        return result
    }

    private static func mark(_ item: NSPasteboardItem) {
        item.setString(UUID().uuidString, forType: CaptureService.internalType)
    }

    static func markPublication(_ id: UUID, in items: [NSPasteboardItem]) {
        for item in items { item.setString(id.uuidString, forType: OwnedFilePublicationCoordinator.pasteboardType) }
    }

    static func supportsPlainText(_ record: ClipboardRecord) -> Bool {
        guard record.kind != .image && record.kind != .file else { return false }
        let types = Set(record.parts.flatMap(\.representations).map(\.typeIdentifier))
        return types.isDisjoint(with: [NSPasteboard.PasteboardType.pdf.rawValue, "public.pdf"]) || types.contains(NSPasteboard.PasteboardType.string.rawValue)
    }
}
