import ClipShelfCore
import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers
import XCTest
@testable import ClipShelf

/// Independent APNG oracle: chunk offsets, blend/disposal modes, and expected visible
/// frames are specified by hand rather than generated by the ImageIO animation writer.
final class OptimizedAPNGRotationTests: XCTestCase {
    private typealias Pixel = [UInt8]
    private let red: Pixel = [255, 0, 0, 255]
    private let green: Pixel = [0, 255, 0, 255]
    private let blue: Pixel = [0, 0, 255, 255]
    private let yellow: Pixel = [255, 255, 0, 255]
    private let magenta: Pixel = [255, 0, 255, 255]
    private let cyan: Pixel = [0, 255, 255, 255]
    private let clear: Pixel = [0, 0, 0, 0]

    private func integer(_ value: UInt32) -> Data {
        Data([UInt8(truncatingIfNeeded: value >> 24), UInt8(truncatingIfNeeded: value >> 16),
              UInt8(truncatingIfNeeded: value >> 8), UInt8(truncatingIfNeeded: value)])
    }
    private func chunk(_ name: String, _ payload: Data) -> Data {
        let name = Data(name.utf8)
        var crc: UInt32 = 0xffff_ffff
        for byte in name + payload {
            crc ^= UInt32(byte)
            for _ in 0..<8 { crc = (crc & 1) == 0 ? crc >> 1 : (crc >> 1) ^ 0xedb8_8320 }
        }
        return integer(UInt32(payload.count)) + name + payload + integer(crc ^ 0xffff_ffff)
    }
    private func png(width: Int, height: Int, pixels: [Pixel]) throws -> Data {
        let source = Data(pixels.flatMap { $0 })
        let image = try XCTUnwrap(CGImage(width: width, height: height, bitsPerComponent: 8, bitsPerPixel: 32,
            bytesPerRow: width * 4, space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGBitmapInfo(rawValue: CGImageAlphaInfo.last.rawValue),
            provider: XCTUnwrap(CGDataProvider(data: source as CFData)), decode: nil, shouldInterpolate: false, intent: .defaultIntent))
        let output = NSMutableData()
        let writer = try XCTUnwrap(CGImageDestinationCreateWithData(output, UTType.png.identifier as CFString, 1, nil))
        CGImageDestinationAddImage(writer, image, nil)
        XCTAssertTrue(CGImageDestinationFinalize(writer))
        return output as Data
    }
    private func chunks(_ data: Data) throws -> [(String, Data)] {
        var result: [(String, Data)] = [], cursor = 8
        while cursor < data.count {
            guard data.count - cursor >= 12 else { throw FixtureError.invalidPNG }
            let length = data[cursor..<(cursor + 4)].reduce(0) { ($0 << 8) | Int($1) }
            guard length <= data.count - cursor - 12,
                  let name = String(data: data[(cursor + 4)..<(cursor + 8)], encoding: .ascii) else { throw FixtureError.invalidPNG }
            result.append((name, Data(data[(cursor + 8)..<(cursor + 8 + length)])))
            cursor += length + 12
        }
        return result
    }
    private enum FixtureError: Error { case invalidPNG }

    private func fixture() throws -> (data: Data, expected: [[Pixel]]) {
        let frames: [(width: Int, height: Int, x: Int, y: Int, dispose: UInt8, blend: UInt8, pixels: [Pixel])] = [
            (3, 2, 0, 0, 0, 0, [red, green, blue, yellow, magenta, cyan]),
            // Blend a half-transparent blue over the top-middle green; restore the original afterward.
            (1, 1, 1, 0, 2, 1, [[0, 0, 255, 128]]),
            // Source replacement must clear the bottom-left pixel. Disposal clears this entire patch.
            (2, 1, 0, 1, 1, 0, [clear, red]),
            // The two cleared pixels must remain clear, independent of this offset yellow patch.
            (1, 1, 2, 1, 0, 1, [yellow]),
        ]
        let expected: [[Pixel]] = [
            [red, green, blue, yellow, magenta, cyan],
            [red, [0, 127, 128, 255], blue, yellow, magenta, cyan],
            [red, green, blue, clear, red, cyan],
            [red, green, blue, clear, clear, yellow],
        ]
        let images = try frames.map { try chunks(png(width: $0.width, height: $0.height, pixels: $0.pixels)) }
        let ihdr = try XCTUnwrap(images[0].first { $0.0 == "IHDR" }?.1)
        XCTAssertEqual(ihdr[8], 8); XCTAssertEqual(ihdr[9], 6, "Every compressed patch uses RGBA PNG samples")
        var result = Data([137, 80, 78, 71, 13, 10, 26, 10])
        result.append(chunk("IHDR", ihdr))
        for (name, payload) in images[0] where ["sRGB", "iCCP", "gAMA", "cHRM"].contains(name) { result.append(chunk(name, payload)) }
        result.append(chunk("acTL", integer(UInt32(frames.count)) + integer(3)))
        var sequence: UInt32 = 0
        for (index, frame) in frames.enumerated() {
            let patchHeader = try XCTUnwrap(images[index].first { $0.0 == "IHDR" }?.1)
            XCTAssertEqual(patchHeader.suffix(from: 8), ihdr.suffix(from: 8), "Patch encoding must share the canvas sample format")
            var control = integer(sequence); sequence += 1
            control.append(integer(UInt32(frame.width))); control.append(integer(UInt32(frame.height)))
            control.append(integer(UInt32(frame.x))); control.append(integer(UInt32(frame.y)))
            control.append(contentsOf: [0, UInt8([7, 13, 17, 21][index]), 0, 100, frame.dispose, frame.blend])
            result.append(chunk("fcTL", control))
            let compressed = images[index].filter { $0.0 == "IDAT" }.reduce(Data()) { $0 + $1.1 }
            XCTAssertFalse(compressed.isEmpty)
            if index == 0 { result.append(chunk("IDAT", compressed)) }
            else { result.append(chunk("fdAT", integer(sequence) + compressed)); sequence += 1 }
        }
        result.append(chunk("IEND", Data()))
        return (result, expected)
    }

    private func pixels(_ image: CGImage) throws -> [Pixel] {
        let context = try XCTUnwrap(CGContext(data: nil, width: image.width, height: image.height, bitsPerComponent: 8,
            bytesPerRow: image.width * 4, space: CGColorSpace(name: CGColorSpace.sRGB)!,
            bitmapInfo: CGBitmapInfo.byteOrder32Big.rawValue | CGImageAlphaInfo.premultipliedLast.rawValue))
        context.setBlendMode(.copy); context.interpolationQuality = .none
        context.draw(image, in: CGRect(x: 0, y: 0, width: image.width, height: image.height))
        let data = try XCTUnwrap(context.data).assumingMemoryBound(to: UInt8.self)
        return (0..<(image.width * image.height)).map { Array(UnsafeBufferPointer(start: data + $0 * 4, count: 4)) }
    }
    private func assertPixels(_ actual: [Pixel], _ expected: [Pixel], label: String,
                              file: StaticString = #filePath, line: UInt = #line) {
        XCTAssertEqual(actual.count, expected.count, label, file: file, line: line)
        for (offset, pair) in zip(actual, expected).enumerated() {
            for channel in 0..<4 {
                XCTAssertEqual(Int(pair.0[channel]), Int(pair.1[channel]), accuracy: 1,
                               "\(label), pixel \(offset), channel \(channel)", file: file, line: line)
            }
        }
    }

    func testSingleFrameAPNGKeepsLoopAndDelayOrRejectsWithoutFlattening() throws {
        let original = try fixture()
        var input = Data([137, 80, 78, 71, 13, 10, 26, 10])
        var hasControl = false
        for (name, payload) in try chunks(original.data) {
            if name == "acTL" { input.append(chunk(name, integer(1) + integer(3))) }
            else if name == "fcTL" {
                if hasControl { continue }
                hasControl = true; input.append(chunk(name, payload))
            } else if name != "fdAT" { input.append(chunk(name, payload)) }
        }
        let source = try XCTUnwrap(CGImageSourceCreateWithData(input as CFData, nil))
        XCTAssertEqual(CGImageSourceGetCount(source), 1)
        let record = ClipboardRecord(text: "one-frame APNG", parts: [.init(representations: [.init(typeIdentifier: "public.png", data: input)])])
        let saved: ClipboardRecord
        do { saved = try ImageRotationPlan.rotatedRecord(record) }
        catch ImageRotationError.unsupportedAnimation {
            XCTAssertEqual(record.parts[0].representations[0].data, input)
            return // An encoder that flattens the animation must fail before publishing.
        }
        let output = try XCTUnwrap(CGImageSourceCreateWithData(saved.parts[0].representations[0].data as CFData, nil))
        XCTAssertEqual(CGImageSourceGetCount(output), 1)
        let global = CGImageSourceCopyProperties(output, nil) as? [CFString: Any]
        XCTAssertEqual(((global?[kCGImagePropertyPNGDictionary] as? [CFString: Any])?[kCGImagePropertyAPNGLoopCount] as? NSNumber)?.intValue, 3)
        let properties = CGImageSourceCopyPropertiesAtIndex(output, 0, nil) as? [CFString: Any]
        XCTAssertEqual(((properties?[kCGImagePropertyPNGDictionary] as? [CFString: Any])?[kCGImagePropertyAPNGUnclampedDelayTime] as? NSNumber)?.doubleValue ?? -1, 0.07, accuracy: 0.00001)
    }

    func testOffsetBlendOverAndRestorePreviousBackgroundFramesRotateVisuallyOrRejectExplicitly() throws {
        let fixture = try fixture()
        let source = try XCTUnwrap(CGImageSourceCreateWithData(fixture.data as CFData, nil))
        XCTAssertEqual(CGImageSourceGetStatus(source), .statusComplete)
        XCTAssertEqual(CGImageSourceGetCount(source), 4)
        // Validate the independent expected composites before asking the application to rotate.
        for index in 0..<4 {
            let frame = try XCTUnwrap(CGImageSourceCreateImageAtIndex(source, index, nil))
            XCTAssertEqual(frame.width, 3); XCTAssertEqual(frame.height, 2)
            assertPixels(try pixels(frame), fixture.expected[index], label: "source frame \(index)")
        }
        let record = ClipboardRecord(text: "optimized APNG", parts: [.init(representations: [.init(typeIdentifier: "public.png", data: fixture.data)])])
        let saved: ClipboardRecord
        do { saved = try ImageRotationPlan.rotatedRecord(record) }
        catch ImageRotationError.unsupportedAnimation {
            XCTAssertEqual(record.parts[0].representations[0].data, fixture.data)
            print("APNG optimized fixture: explicit unsupportedAnimation, original preserved")
            return
        }
        let rotated = try XCTUnwrap(CGImageSourceCreateWithData(saved.parts[0].representations[0].data as CFData, nil))
        XCTAssertEqual(CGImageSourceGetCount(rotated), 4)
        let global = CGImageSourceCopyProperties(rotated, nil) as? [CFString: Any]
        XCTAssertEqual(((global?[kCGImagePropertyPNGDictionary] as? [CFString: Any])?[kCGImagePropertyAPNGLoopCount] as? NSNumber)?.intValue, 3)
        for index in 0..<4 {
            let frame = try XCTUnwrap(CGImageSourceCreateImageAtIndex(rotated, index, nil))
            XCTAssertEqual(frame.width, 2); XCTAssertEqual(frame.height, 3)
            let before = fixture.expected[index]
            let expected = (0..<3).flatMap { y in (0..<2).map { x in before[x * 3 + 2 - y] } }
            assertPixels(try pixels(frame), expected, label: "rotated frame \(index)")
            let properties = CGImageSourceCopyPropertiesAtIndex(rotated, index, nil) as? [CFString: Any]
            XCTAssertEqual(((properties?[kCGImagePropertyPNGDictionary] as? [CFString: Any])?[kCGImagePropertyAPNGUnclampedDelayTime] as? NSNumber)?.doubleValue ?? -1,
                           [0.07, 0.13, 0.17, 0.21][index], accuracy: 0.000_001)
        }
    }
}
